version: '3'
services:
  sso_apps:
    container_name: sso_apps
    build: .docker/php
    ports:
      - 5173:5173
    volumes:
      - ./src:/var/www:cached
    networks:
      - internal
    depends_on:
      - sso_mysql

  sso_nginx:
    container_name: sso_nginx
    image: nginx
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./src:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    dns:
      - ${BAIDUDNS}
      - ${GOOGLEDNS}
    depends_on:
      - sso_apps
      - sso_mysql
    networks:
      - internal

  sso_mysql:
    container_name: sso_mysql
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'sushant'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'laravel_db_name'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal

  npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - internal

networks:
  internal:
    driver: bridge
